// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptJob(arg1) {
  return window['go']['main']['App']['AcceptJob'](arg1);
}

export function BuyModule(arg1) {
  return window['go']['main']['App']['BuyModule'](arg1);
}

export function DropJob(arg1) {
  return window['go']['main']['App']['DropJob'](arg1);
}

export function GetAvailableContracts() {
  return window['go']['main']['App']['GetAvailableContracts']();
}

export function GetModules() {
  return window['go']['main']['App']['GetModules']();
}

export function GetPlanets() {
  return window['go']['main']['App']['GetPlanets']();
}

export function GetShipState() {
  return window['go']['main']['App']['GetShipState']();
}

export function GetTravelQuote(arg1) {
  return window['go']['main']['App']['GetTravelQuote'](arg1);
}

export function Refuel() {
  return window['go']['main']['App']['Refuel']();
}

export function Travel(arg1) {
  return window['go']['main']['App']['Travel'](arg1);
}
