// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptJob(arg1:string):Promise<any>;

export function BuyModule(arg1:string):Promise<any>;

export function DropJob(arg1:string):Promise<any>;

export function GetAvailableContracts():Promise<any>;

export function GetModules():Promise<any>;

export function GetPlanets():Promise<any>;

export function GetShipState():Promise<any>;

export function GetTravelQuote(arg1:string):Promise<any>;

export function Refuel():Promise<any>;

export function Travel(arg1:string):Promise<any>;
