// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game} from '../models';
import {main} from '../models';

export function AcceptJob(arg1:string):Promise<boolean>;

export function BuyModule(arg1:string):Promise<boolean>;

export function DropJob(arg1:string):Promise<boolean>;

export function GetAvailableContracts():Promise<Array<game.Contract>>;

export function GetModules():Promise<Array<game.ShipModule>>;

export function GetPlanets():Promise<Array<game.Planet>>;

export function GetShipState():Promise<game.Ship>;

export function GetTravelQuote(arg1:string):Promise<main.TravelQuoteResponse>;

export function Refuel():Promise<boolean>;

export function Travel(arg1:string):Promise<main.TravelResponse>;
